name: Release

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Magisk Module
        run: zip -r emagic.zip . -x ".git/*" "build.sh" ".gitignore" "*zip"

      - name: Get current date and time
        id: get_date
        run: echo "::set-output name=date::$(date '+%Y%m%d-%H%M%S')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: emagic-main-${{ steps.get_date.outputs.date }}
          draft: false 
          prerelease: false

      - name: Upload
        if: ${{ steps.create_release.outputs.release_id }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: emagic.zip
          asset_name: emagic-main-${{ steps.get_date.outputs.date }}.zip