name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build eMagic
        run: zip -r emagic.zip . -x ".git/*" "build.sh" ".gitignore" "*zip"

      - name: Get commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          release_name: "Latest Build (${{ env.sha_short }})"
          files: emagic.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false