name: Release Magisk Module

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build module
        run: zip -r emagic.zip . -x ".git/*" "build.sh" ".gitignore" "*zip"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: eMagic ${{ github.ref }}
          body: ${{ github.ref }} # Simple release notes
          draft: false

      - name: Upload
        if: ${{ steps.create_release.outputs.release_id }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: emagic.zip
          asset_name: emagic-${{ github.ref }}.zip